# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create_new_game_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateNewGameDialog(object):
    def setupUi(self, CreateNewGameDialog):
        CreateNewGameDialog.setObjectName("CreateNewGameDialog")
        CreateNewGameDialog.resize(460, 460)
        CreateNewGameDialog.setAutoFillBackground(False)
        self.buttonBox = QtWidgets.QDialogButtonBox(CreateNewGameDialog)
        self.buttonBox.setGeometry(QtCore.QRect(280, 410, 161, 31))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.label_A = QtWidgets.QLabel(CreateNewGameDialog)
        self.label_A.setGeometry(QtCore.QRect(20, 20, 32, 32))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_A.setFont(font)
        self.label_A.setStyleSheet("color: #8e2426;")
        self.label_A.setAlignment(QtCore.Qt.AlignCenter)
        self.label_A.setObjectName("label_A")
        self.label_B = QtWidgets.QLabel(CreateNewGameDialog)
        self.label_B.setGeometry(QtCore.QRect(20, 52, 32, 32))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_B.setFont(font)
        self.label_B.setStyleSheet("color: #8e2426;")
        self.label_B.setAlignment(QtCore.Qt.AlignCenter)
        self.label_B.setObjectName("label_B")
        self.label_C = QtWidgets.QLabel(CreateNewGameDialog)
        self.label_C.setGeometry(QtCore.QRect(20, 84, 32, 32))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_C.setFont(font)
        self.label_C.setStyleSheet("color: #8e2426;")
        self.label_C.setAlignment(QtCore.Qt.AlignCenter)
        self.label_C.setObjectName("label_C")
        self.label_D = QtWidgets.QLabel(CreateNewGameDialog)
        self.label_D.setGeometry(QtCore.QRect(20, 116, 32, 32))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_D.setFont(font)
        self.label_D.setStyleSheet("color: #8e2426;")
        self.label_D.setAlignment(QtCore.Qt.AlignCenter)
        self.label_D.setObjectName("label_D")
        self.label_E = QtWidgets.QLabel(CreateNewGameDialog)
        self.label_E.setGeometry(QtCore.QRect(20, 148, 32, 32))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_E.setFont(font)
        self.label_E.setStyleSheet("color: #8e2426;")
        self.label_E.setAlignment(QtCore.Qt.AlignCenter)
        self.label_E.setObjectName("label_E")
        self.label_F = QtWidgets.QLabel(CreateNewGameDialog)
        self.label_F.setGeometry(QtCore.QRect(20, 180, 32, 32))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_F.setFont(font)
        self.label_F.setStyleSheet("color: #8e2426;")
        self.label_F.setAlignment(QtCore.Qt.AlignCenter)
        self.label_F.setObjectName("label_F")
        self.label_G = QtWidgets.QLabel(CreateNewGameDialog)
        self.label_G.setGeometry(QtCore.QRect(20, 212, 32, 32))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_G.setFont(font)
        self.label_G.setStyleSheet("color: #8e2426;")
        self.label_G.setAlignment(QtCore.Qt.AlignCenter)
        self.label_G.setObjectName("label_G")
        self.label_H = QtWidgets.QLabel(CreateNewGameDialog)
        self.label_H.setGeometry(QtCore.QRect(20, 244, 32, 32))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_H.setFont(font)
        self.label_H.setStyleSheet("color: #8e2426;")
        self.label_H.setAlignment(QtCore.Qt.AlignCenter)
        self.label_H.setObjectName("label_H")
        self.label_1 = QtWidgets.QLabel(CreateNewGameDialog)
        self.label_1.setGeometry(QtCore.QRect(52, 276, 32, 32))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_1.setFont(font)
        self.label_1.setStyleSheet("color: #8e2426;")
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(CreateNewGameDialog)
        self.label_2.setGeometry(QtCore.QRect(84, 276, 32, 32))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #8e2426;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(CreateNewGameDialog)
        self.label_3.setGeometry(QtCore.QRect(116, 276, 32, 32))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: #8e2426;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(CreateNewGameDialog)
        self.label_4.setGeometry(QtCore.QRect(148, 276, 32, 32))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: #8e2426;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(CreateNewGameDialog)
        self.label_5.setGeometry(QtCore.QRect(181, 276, 31, 32))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: #8e2426;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(CreateNewGameDialog)
        self.label_6.setGeometry(QtCore.QRect(212, 276, 32, 32))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: #8e2426;")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(CreateNewGameDialog)
        self.label_7.setGeometry(QtCore.QRect(244, 276, 32, 32))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: #8e2426;")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(CreateNewGameDialog)
        self.label_8.setGeometry(QtCore.QRect(276, 276, 32, 32))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: #8e2426;")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.area = QtWidgets.QLabel(CreateNewGameDialog)
        self.area.setGeometry(QtCore.QRect(52, 20, 256, 256))
        self.area.setStyleSheet("")
        self.area.setText("")
        self.area.setObjectName("area")
        self.widget = QtWidgets.QWidget(CreateNewGameDialog)
        self.widget.setGeometry(QtCore.QRect(10, 310, 271, 131))
        self.widget.setObjectName("widget")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.widget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 261, 114))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_players_1 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_players_1.sizePolicy().hasHeightForWidth())
        self.label_players_1.setSizePolicy(sizePolicy)
        self.label_players_1.setMinimumSize(QtCore.QSize(150, 0))
        self.label_players_1.setTextFormat(QtCore.Qt.RichText)
        self.label_players_1.setScaledContents(True)
        self.label_players_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_players_1.setWordWrap(False)
        self.label_players_1.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_players_1.setObjectName("label_players_1")
        self.gridLayout_3.addWidget(self.label_players_1, 0, 0, 1, 3)
        self.label_players_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_players_2.sizePolicy().hasHeightForWidth())
        self.label_players_2.setSizePolicy(sizePolicy)
        self.label_players_2.setMinimumSize(QtCore.QSize(150, 0))
        self.label_players_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_players_2.setObjectName("label_players_2")
        self.gridLayout_3.addWidget(self.label_players_2, 1, 0, 1, 3)
        self.lineSecond = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineSecond.setObjectName("lineSecond")
        self.gridLayout_3.addWidget(self.lineSecond, 5, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(90, 0))
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 5, 2, 1, 1)
        self.second = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.second.sizePolicy().hasHeightForWidth())
        self.second.setSizePolicy(sizePolicy)
        self.second.setText("")
        self.second.setObjectName("second")
        self.gridLayout_3.addWidget(self.second, 5, 0, 1, 1)
        self.lineFirst = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineFirst.setObjectName("lineFirst")
        self.gridLayout_3.addWidget(self.lineFirst, 4, 1, 1, 1)
        self.first = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.first.sizePolicy().hasHeightForWidth())
        self.first.setSizePolicy(sizePolicy)
        self.first.setText("")
        self.first.setChecked(True)
        self.first.setObjectName("first")
        self.gridLayout_3.addWidget(self.first, 4, 0, 1, 1)
        self.label_players_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_players_3.sizePolicy().hasHeightForWidth())
        self.label_players_3.setSizePolicy(sizePolicy)
        self.label_players_3.setMinimumSize(QtCore.QSize(150, 0))
        self.label_players_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_players_3.setObjectName("label_players_3")
        self.gridLayout_3.addWidget(self.label_players_3, 2, 0, 1, 3)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(90, 0))
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 4, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 3, 0, 1, 3)
        self.widget_2 = QtWidgets.QWidget(CreateNewGameDialog)
        self.widget_2.setGeometry(QtCore.QRect(320, 20, 161, 321))
        self.widget_2.setObjectName("widget_2")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.widget_2)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 0, 121, 281))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.whiteBishop = QtWidgets.QRadioButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.whiteBishop.sizePolicy().hasHeightForWidth())
        self.whiteBishop.setSizePolicy(sizePolicy)
        self.whiteBishop.setMinimumSize(QtCore.QSize(34, 34))
        self.whiteBishop.setText("")
        self.whiteBishop.setObjectName("whiteBishop")
        self.gridLayout_4.addWidget(self.whiteBishop, 3, 0, 1, 1)
        self.blackRook = QtWidgets.QRadioButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blackRook.sizePolicy().hasHeightForWidth())
        self.blackRook.setSizePolicy(sizePolicy)
        self.blackRook.setMinimumSize(QtCore.QSize(34, 34))
        self.blackRook.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.blackRook.setText("")
        self.blackRook.setObjectName("blackRook")
        self.gridLayout_4.addWidget(self.blackRook, 4, 2, 1, 1)
        self.imgPawn = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imgPawn.sizePolicy().hasHeightForWidth())
        self.imgPawn.setSizePolicy(sizePolicy)
        self.imgPawn.setMinimumSize(QtCore.QSize(34, 34))
        self.imgPawn.setText("")
        self.imgPawn.setAlignment(QtCore.Qt.AlignCenter)
        self.imgPawn.setObjectName("imgPawn")
        self.gridLayout_4.addWidget(self.imgPawn, 6, 1, 1, 1)
        self.blackBishop = QtWidgets.QRadioButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blackBishop.sizePolicy().hasHeightForWidth())
        self.blackBishop.setSizePolicy(sizePolicy)
        self.blackBishop.setMinimumSize(QtCore.QSize(34, 34))
        self.blackBishop.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.blackBishop.setText("")
        self.blackBishop.setObjectName("blackBishop")
        self.gridLayout_4.addWidget(self.blackBishop, 3, 2, 1, 1)
        self.label_black_or_white = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_black_or_white.sizePolicy().hasHeightForWidth())
        self.label_black_or_white.setSizePolicy(sizePolicy)
        self.label_black_or_white.setMinimumSize(QtCore.QSize(102, 34))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_black_or_white.setFont(font)
        self.label_black_or_white.setTextFormat(QtCore.Qt.AutoText)
        self.label_black_or_white.setAlignment(QtCore.Qt.AlignCenter)
        self.label_black_or_white.setObjectName("label_black_or_white")
        self.gridLayout_4.addWidget(self.label_black_or_white, 0, 0, 1, 3)
        self.imgBishop = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imgBishop.sizePolicy().hasHeightForWidth())
        self.imgBishop.setSizePolicy(sizePolicy)
        self.imgBishop.setMinimumSize(QtCore.QSize(34, 34))
        self.imgBishop.setText("")
        self.imgBishop.setAlignment(QtCore.Qt.AlignCenter)
        self.imgBishop.setObjectName("imgBishop")
        self.gridLayout_4.addWidget(self.imgBishop, 3, 1, 1, 1)
        self.whiteKing = QtWidgets.QRadioButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.whiteKing.sizePolicy().hasHeightForWidth())
        self.whiteKing.setSizePolicy(sizePolicy)
        self.whiteKing.setMinimumSize(QtCore.QSize(34, 34))
        self.whiteKing.setText("")
        self.whiteKing.setChecked(True)
        self.whiteKing.setObjectName("whiteKing")
        self.gridLayout_4.addWidget(self.whiteKing, 1, 0, 1, 1)
        self.blackKnight = QtWidgets.QRadioButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blackKnight.sizePolicy().hasHeightForWidth())
        self.blackKnight.setSizePolicy(sizePolicy)
        self.blackKnight.setMinimumSize(QtCore.QSize(34, 34))
        self.blackKnight.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.blackKnight.setText("")
        self.blackKnight.setObjectName("blackKnight")
        self.gridLayout_4.addWidget(self.blackKnight, 5, 2, 1, 1)
        self.blackQueen = QtWidgets.QRadioButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blackQueen.sizePolicy().hasHeightForWidth())
        self.blackQueen.setSizePolicy(sizePolicy)
        self.blackQueen.setMinimumSize(QtCore.QSize(34, 34))
        self.blackQueen.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.blackQueen.setText("")
        self.blackQueen.setObjectName("blackQueen")
        self.gridLayout_4.addWidget(self.blackQueen, 2, 2, 1, 1)
        self.imgQueen = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imgQueen.sizePolicy().hasHeightForWidth())
        self.imgQueen.setSizePolicy(sizePolicy)
        self.imgQueen.setMinimumSize(QtCore.QSize(34, 34))
        self.imgQueen.setText("")
        self.imgQueen.setAlignment(QtCore.Qt.AlignCenter)
        self.imgQueen.setObjectName("imgQueen")
        self.gridLayout_4.addWidget(self.imgQueen, 2, 1, 1, 1)
        self.whiteQueen = QtWidgets.QRadioButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.whiteQueen.sizePolicy().hasHeightForWidth())
        self.whiteQueen.setSizePolicy(sizePolicy)
        self.whiteQueen.setMinimumSize(QtCore.QSize(34, 34))
        self.whiteQueen.setText("")
        self.whiteQueen.setObjectName("whiteQueen")
        self.gridLayout_4.addWidget(self.whiteQueen, 2, 0, 1, 1)
        self.clear = QtWidgets.QRadioButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clear.sizePolicy().hasHeightForWidth())
        self.clear.setSizePolicy(sizePolicy)
        self.clear.setMinimumSize(QtCore.QSize(0, 34))
        self.clear.setChecked(False)
        self.clear.setObjectName("clear")
        self.gridLayout_4.addWidget(self.clear, 7, 0, 1, 3)
        self.whitePawn = QtWidgets.QRadioButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.whitePawn.sizePolicy().hasHeightForWidth())
        self.whitePawn.setSizePolicy(sizePolicy)
        self.whitePawn.setMinimumSize(QtCore.QSize(34, 34))
        self.whitePawn.setText("")
        self.whitePawn.setObjectName("whitePawn")
        self.gridLayout_4.addWidget(self.whitePawn, 6, 0, 1, 1)
        self.imgKing = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imgKing.sizePolicy().hasHeightForWidth())
        self.imgKing.setSizePolicy(sizePolicy)
        self.imgKing.setMinimumSize(QtCore.QSize(34, 34))
        self.imgKing.setText("")
        self.imgKing.setAlignment(QtCore.Qt.AlignCenter)
        self.imgKing.setObjectName("imgKing")
        self.gridLayout_4.addWidget(self.imgKing, 1, 1, 1, 1)
        self.blackKing = QtWidgets.QRadioButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blackKing.sizePolicy().hasHeightForWidth())
        self.blackKing.setSizePolicy(sizePolicy)
        self.blackKing.setMinimumSize(QtCore.QSize(34, 34))
        self.blackKing.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.blackKing.setText("")
        self.blackKing.setObjectName("blackKing")
        self.gridLayout_4.addWidget(self.blackKing, 1, 2, 1, 1)
        self.imgRook = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imgRook.sizePolicy().hasHeightForWidth())
        self.imgRook.setSizePolicy(sizePolicy)
        self.imgRook.setMinimumSize(QtCore.QSize(34, 34))
        self.imgRook.setText("")
        self.imgRook.setAlignment(QtCore.Qt.AlignCenter)
        self.imgRook.setObjectName("imgRook")
        self.gridLayout_4.addWidget(self.imgRook, 4, 1, 1, 1)
        self.blackPawn = QtWidgets.QRadioButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blackPawn.sizePolicy().hasHeightForWidth())
        self.blackPawn.setSizePolicy(sizePolicy)
        self.blackPawn.setMinimumSize(QtCore.QSize(34, 34))
        self.blackPawn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.blackPawn.setText("")
        self.blackPawn.setObjectName("blackPawn")
        self.gridLayout_4.addWidget(self.blackPawn, 6, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 8, 0, 1, 1)
        self.whiteRook = QtWidgets.QRadioButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.whiteRook.sizePolicy().hasHeightForWidth())
        self.whiteRook.setSizePolicy(sizePolicy)
        self.whiteRook.setMinimumSize(QtCore.QSize(34, 34))
        self.whiteRook.setText("")
        self.whiteRook.setChecked(False)
        self.whiteRook.setObjectName("whiteRook")
        self.gridLayout_4.addWidget(self.whiteRook, 4, 0, 1, 1)
        self.whiteKnight = QtWidgets.QRadioButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.whiteKnight.sizePolicy().hasHeightForWidth())
        self.whiteKnight.setSizePolicy(sizePolicy)
        self.whiteKnight.setMinimumSize(QtCore.QSize(34, 34))
        self.whiteKnight.setText("")
        self.whiteKnight.setObjectName("whiteKnight")
        self.gridLayout_4.addWidget(self.whiteKnight, 5, 0, 1, 1)
        self.imgKnight = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imgKnight.sizePolicy().hasHeightForWidth())
        self.imgKnight.setSizePolicy(sizePolicy)
        self.imgKnight.setMinimumSize(QtCore.QSize(34, 34))
        self.imgKnight.setText("")
        self.imgKnight.setAlignment(QtCore.Qt.AlignCenter)
        self.imgKnight.setObjectName("imgKnight")
        self.gridLayout_4.addWidget(self.imgKnight, 5, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 3, 3, 1, 1)
        self.A1 = QtWidgets.QLabel(CreateNewGameDialog)
        self.A1.setGeometry(QtCore.QRect(52, 20, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.A1.sizePolicy().hasHeightForWidth())
        self.A1.setSizePolicy(sizePolicy)
        self.A1.setText("")
        self.A1.setObjectName("A1")
        self.A2 = QtWidgets.QLabel(CreateNewGameDialog)
        self.A2.setGeometry(QtCore.QRect(84, 20, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.A2.sizePolicy().hasHeightForWidth())
        self.A2.setSizePolicy(sizePolicy)
        self.A2.setText("")
        self.A2.setObjectName("A2")
        self.A3 = QtWidgets.QLabel(CreateNewGameDialog)
        self.A3.setGeometry(QtCore.QRect(116, 20, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.A3.sizePolicy().hasHeightForWidth())
        self.A3.setSizePolicy(sizePolicy)
        self.A3.setText("")
        self.A3.setObjectName("A3")
        self.A4 = QtWidgets.QLabel(CreateNewGameDialog)
        self.A4.setGeometry(QtCore.QRect(148, 20, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.A4.sizePolicy().hasHeightForWidth())
        self.A4.setSizePolicy(sizePolicy)
        self.A4.setText("")
        self.A4.setObjectName("A4")
        self.A5 = QtWidgets.QLabel(CreateNewGameDialog)
        self.A5.setGeometry(QtCore.QRect(180, 20, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.A5.sizePolicy().hasHeightForWidth())
        self.A5.setSizePolicy(sizePolicy)
        self.A5.setText("")
        self.A5.setObjectName("A5")
        self.A6 = QtWidgets.QLabel(CreateNewGameDialog)
        self.A6.setGeometry(QtCore.QRect(212, 20, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.A6.sizePolicy().hasHeightForWidth())
        self.A6.setSizePolicy(sizePolicy)
        self.A6.setText("")
        self.A6.setObjectName("A6")
        self.A7 = QtWidgets.QLabel(CreateNewGameDialog)
        self.A7.setGeometry(QtCore.QRect(244, 20, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.A7.sizePolicy().hasHeightForWidth())
        self.A7.setSizePolicy(sizePolicy)
        self.A7.setText("")
        self.A7.setObjectName("A7")
        self.A8 = QtWidgets.QLabel(CreateNewGameDialog)
        self.A8.setGeometry(QtCore.QRect(276, 20, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.A8.sizePolicy().hasHeightForWidth())
        self.A8.setSizePolicy(sizePolicy)
        self.A8.setText("")
        self.A8.setObjectName("A8")
        self.B1 = QtWidgets.QLabel(CreateNewGameDialog)
        self.B1.setGeometry(QtCore.QRect(52, 52, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.B1.sizePolicy().hasHeightForWidth())
        self.B1.setSizePolicy(sizePolicy)
        self.B1.setText("")
        self.B1.setObjectName("B1")
        self.B2 = QtWidgets.QLabel(CreateNewGameDialog)
        self.B2.setGeometry(QtCore.QRect(84, 52, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.B2.sizePolicy().hasHeightForWidth())
        self.B2.setSizePolicy(sizePolicy)
        self.B2.setText("")
        self.B2.setObjectName("B2")
        self.B3 = QtWidgets.QLabel(CreateNewGameDialog)
        self.B3.setGeometry(QtCore.QRect(116, 52, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.B3.sizePolicy().hasHeightForWidth())
        self.B3.setSizePolicy(sizePolicy)
        self.B3.setText("")
        self.B3.setObjectName("B3")
        self.B7 = QtWidgets.QLabel(CreateNewGameDialog)
        self.B7.setGeometry(QtCore.QRect(244, 52, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.B7.sizePolicy().hasHeightForWidth())
        self.B7.setSizePolicy(sizePolicy)
        self.B7.setText("")
        self.B7.setObjectName("B7")
        self.B8 = QtWidgets.QLabel(CreateNewGameDialog)
        self.B8.setGeometry(QtCore.QRect(276, 52, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.B8.sizePolicy().hasHeightForWidth())
        self.B8.setSizePolicy(sizePolicy)
        self.B8.setText("")
        self.B8.setObjectName("B8")
        self.B4 = QtWidgets.QLabel(CreateNewGameDialog)
        self.B4.setGeometry(QtCore.QRect(148, 52, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.B4.sizePolicy().hasHeightForWidth())
        self.B4.setSizePolicy(sizePolicy)
        self.B4.setText("")
        self.B4.setObjectName("B4")
        self.B6 = QtWidgets.QLabel(CreateNewGameDialog)
        self.B6.setGeometry(QtCore.QRect(212, 52, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.B6.sizePolicy().hasHeightForWidth())
        self.B6.setSizePolicy(sizePolicy)
        self.B6.setText("")
        self.B6.setObjectName("B6")
        self.B5 = QtWidgets.QLabel(CreateNewGameDialog)
        self.B5.setGeometry(QtCore.QRect(180, 52, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.B5.sizePolicy().hasHeightForWidth())
        self.B5.setSizePolicy(sizePolicy)
        self.B5.setText("")
        self.B5.setObjectName("B5")
        self.C1 = QtWidgets.QLabel(CreateNewGameDialog)
        self.C1.setGeometry(QtCore.QRect(52, 84, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.C1.sizePolicy().hasHeightForWidth())
        self.C1.setSizePolicy(sizePolicy)
        self.C1.setText("")
        self.C1.setObjectName("C1")
        self.C2 = QtWidgets.QLabel(CreateNewGameDialog)
        self.C2.setGeometry(QtCore.QRect(84, 84, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.C2.sizePolicy().hasHeightForWidth())
        self.C2.setSizePolicy(sizePolicy)
        self.C2.setText("")
        self.C2.setObjectName("C2")
        self.C7 = QtWidgets.QLabel(CreateNewGameDialog)
        self.C7.setGeometry(QtCore.QRect(244, 84, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.C7.sizePolicy().hasHeightForWidth())
        self.C7.setSizePolicy(sizePolicy)
        self.C7.setText("")
        self.C7.setObjectName("C7")
        self.C3 = QtWidgets.QLabel(CreateNewGameDialog)
        self.C3.setGeometry(QtCore.QRect(116, 84, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.C3.sizePolicy().hasHeightForWidth())
        self.C3.setSizePolicy(sizePolicy)
        self.C3.setText("")
        self.C3.setObjectName("C3")
        self.C4 = QtWidgets.QLabel(CreateNewGameDialog)
        self.C4.setGeometry(QtCore.QRect(148, 84, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.C4.sizePolicy().hasHeightForWidth())
        self.C4.setSizePolicy(sizePolicy)
        self.C4.setText("")
        self.C4.setObjectName("C4")
        self.C6 = QtWidgets.QLabel(CreateNewGameDialog)
        self.C6.setGeometry(QtCore.QRect(212, 84, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.C6.sizePolicy().hasHeightForWidth())
        self.C6.setSizePolicy(sizePolicy)
        self.C6.setText("")
        self.C6.setObjectName("C6")
        self.C5 = QtWidgets.QLabel(CreateNewGameDialog)
        self.C5.setGeometry(QtCore.QRect(180, 84, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.C5.sizePolicy().hasHeightForWidth())
        self.C5.setSizePolicy(sizePolicy)
        self.C5.setText("")
        self.C5.setObjectName("C5")
        self.C8 = QtWidgets.QLabel(CreateNewGameDialog)
        self.C8.setGeometry(QtCore.QRect(276, 84, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.C8.sizePolicy().hasHeightForWidth())
        self.C8.setSizePolicy(sizePolicy)
        self.C8.setText("")
        self.C8.setObjectName("C8")
        self.D6 = QtWidgets.QLabel(CreateNewGameDialog)
        self.D6.setGeometry(QtCore.QRect(212, 116, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D6.sizePolicy().hasHeightForWidth())
        self.D6.setSizePolicy(sizePolicy)
        self.D6.setText("")
        self.D6.setObjectName("D6")
        self.D5 = QtWidgets.QLabel(CreateNewGameDialog)
        self.D5.setGeometry(QtCore.QRect(180, 116, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D5.sizePolicy().hasHeightForWidth())
        self.D5.setSizePolicy(sizePolicy)
        self.D5.setText("")
        self.D5.setObjectName("D5")
        self.D2 = QtWidgets.QLabel(CreateNewGameDialog)
        self.D2.setGeometry(QtCore.QRect(84, 116, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D2.sizePolicy().hasHeightForWidth())
        self.D2.setSizePolicy(sizePolicy)
        self.D2.setText("")
        self.D2.setObjectName("D2")
        self.D4 = QtWidgets.QLabel(CreateNewGameDialog)
        self.D4.setGeometry(QtCore.QRect(148, 116, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D4.sizePolicy().hasHeightForWidth())
        self.D4.setSizePolicy(sizePolicy)
        self.D4.setText("")
        self.D4.setObjectName("D4")
        self.D8 = QtWidgets.QLabel(CreateNewGameDialog)
        self.D8.setGeometry(QtCore.QRect(276, 116, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D8.sizePolicy().hasHeightForWidth())
        self.D8.setSizePolicy(sizePolicy)
        self.D8.setText("")
        self.D8.setObjectName("D8")
        self.D1 = QtWidgets.QLabel(CreateNewGameDialog)
        self.D1.setGeometry(QtCore.QRect(52, 116, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D1.sizePolicy().hasHeightForWidth())
        self.D1.setSizePolicy(sizePolicy)
        self.D1.setText("")
        self.D1.setObjectName("D1")
        self.D3 = QtWidgets.QLabel(CreateNewGameDialog)
        self.D3.setGeometry(QtCore.QRect(116, 116, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D3.sizePolicy().hasHeightForWidth())
        self.D3.setSizePolicy(sizePolicy)
        self.D3.setText("")
        self.D3.setObjectName("D3")
        self.D7 = QtWidgets.QLabel(CreateNewGameDialog)
        self.D7.setGeometry(QtCore.QRect(244, 116, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D7.sizePolicy().hasHeightForWidth())
        self.D7.setSizePolicy(sizePolicy)
        self.D7.setText("")
        self.D7.setObjectName("D7")
        self.E1 = QtWidgets.QLabel(CreateNewGameDialog)
        self.E1.setGeometry(QtCore.QRect(52, 148, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.E1.sizePolicy().hasHeightForWidth())
        self.E1.setSizePolicy(sizePolicy)
        self.E1.setText("")
        self.E1.setObjectName("E1")
        self.E2 = QtWidgets.QLabel(CreateNewGameDialog)
        self.E2.setGeometry(QtCore.QRect(84, 148, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.E2.sizePolicy().hasHeightForWidth())
        self.E2.setSizePolicy(sizePolicy)
        self.E2.setText("")
        self.E2.setObjectName("E2")
        self.E3 = QtWidgets.QLabel(CreateNewGameDialog)
        self.E3.setGeometry(QtCore.QRect(116, 148, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.E3.sizePolicy().hasHeightForWidth())
        self.E3.setSizePolicy(sizePolicy)
        self.E3.setText("")
        self.E3.setObjectName("E3")
        self.E4 = QtWidgets.QLabel(CreateNewGameDialog)
        self.E4.setGeometry(QtCore.QRect(148, 148, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.E4.sizePolicy().hasHeightForWidth())
        self.E4.setSizePolicy(sizePolicy)
        self.E4.setText("")
        self.E4.setObjectName("E4")
        self.E8 = QtWidgets.QLabel(CreateNewGameDialog)
        self.E8.setGeometry(QtCore.QRect(276, 148, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.E8.sizePolicy().hasHeightForWidth())
        self.E8.setSizePolicy(sizePolicy)
        self.E8.setText("")
        self.E8.setObjectName("E8")
        self.E5 = QtWidgets.QLabel(CreateNewGameDialog)
        self.E5.setGeometry(QtCore.QRect(180, 148, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.E5.sizePolicy().hasHeightForWidth())
        self.E5.setSizePolicy(sizePolicy)
        self.E5.setText("")
        self.E5.setObjectName("E5")
        self.E6 = QtWidgets.QLabel(CreateNewGameDialog)
        self.E6.setGeometry(QtCore.QRect(212, 148, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.E6.sizePolicy().hasHeightForWidth())
        self.E6.setSizePolicy(sizePolicy)
        self.E6.setText("")
        self.E6.setObjectName("E6")
        self.E7 = QtWidgets.QLabel(CreateNewGameDialog)
        self.E7.setGeometry(QtCore.QRect(244, 148, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.E7.sizePolicy().hasHeightForWidth())
        self.E7.setSizePolicy(sizePolicy)
        self.E7.setText("")
        self.E7.setObjectName("E7")
        self.F1 = QtWidgets.QLabel(CreateNewGameDialog)
        self.F1.setGeometry(QtCore.QRect(52, 180, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.F1.sizePolicy().hasHeightForWidth())
        self.F1.setSizePolicy(sizePolicy)
        self.F1.setText("")
        self.F1.setObjectName("F1")
        self.F2 = QtWidgets.QLabel(CreateNewGameDialog)
        self.F2.setGeometry(QtCore.QRect(84, 180, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.F2.sizePolicy().hasHeightForWidth())
        self.F2.setSizePolicy(sizePolicy)
        self.F2.setText("")
        self.F2.setObjectName("F2")
        self.F3 = QtWidgets.QLabel(CreateNewGameDialog)
        self.F3.setGeometry(QtCore.QRect(116, 180, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.F3.sizePolicy().hasHeightForWidth())
        self.F3.setSizePolicy(sizePolicy)
        self.F3.setText("")
        self.F3.setObjectName("F3")
        self.F4 = QtWidgets.QLabel(CreateNewGameDialog)
        self.F4.setGeometry(QtCore.QRect(148, 180, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.F4.sizePolicy().hasHeightForWidth())
        self.F4.setSizePolicy(sizePolicy)
        self.F4.setText("")
        self.F4.setObjectName("F4")
        self.F5 = QtWidgets.QLabel(CreateNewGameDialog)
        self.F5.setGeometry(QtCore.QRect(180, 180, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.F5.sizePolicy().hasHeightForWidth())
        self.F5.setSizePolicy(sizePolicy)
        self.F5.setText("")
        self.F5.setObjectName("F5")
        self.F6 = QtWidgets.QLabel(CreateNewGameDialog)
        self.F6.setGeometry(QtCore.QRect(212, 180, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.F6.sizePolicy().hasHeightForWidth())
        self.F6.setSizePolicy(sizePolicy)
        self.F6.setText("")
        self.F6.setObjectName("F6")
        self.F7 = QtWidgets.QLabel(CreateNewGameDialog)
        self.F7.setGeometry(QtCore.QRect(244, 180, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.F7.sizePolicy().hasHeightForWidth())
        self.F7.setSizePolicy(sizePolicy)
        self.F7.setText("")
        self.F7.setObjectName("F7")
        self.F8 = QtWidgets.QLabel(CreateNewGameDialog)
        self.F8.setGeometry(QtCore.QRect(276, 180, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.F8.sizePolicy().hasHeightForWidth())
        self.F8.setSizePolicy(sizePolicy)
        self.F8.setText("")
        self.F8.setObjectName("F8")
        self.G1 = QtWidgets.QLabel(CreateNewGameDialog)
        self.G1.setGeometry(QtCore.QRect(52, 212, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.G1.sizePolicy().hasHeightForWidth())
        self.G1.setSizePolicy(sizePolicy)
        self.G1.setText("")
        self.G1.setObjectName("G1")
        self.G2 = QtWidgets.QLabel(CreateNewGameDialog)
        self.G2.setGeometry(QtCore.QRect(84, 212, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.G2.sizePolicy().hasHeightForWidth())
        self.G2.setSizePolicy(sizePolicy)
        self.G2.setText("")
        self.G2.setObjectName("G2")
        self.G3 = QtWidgets.QLabel(CreateNewGameDialog)
        self.G3.setGeometry(QtCore.QRect(116, 212, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.G3.sizePolicy().hasHeightForWidth())
        self.G3.setSizePolicy(sizePolicy)
        self.G3.setText("")
        self.G3.setObjectName("G3")
        self.G4 = QtWidgets.QLabel(CreateNewGameDialog)
        self.G4.setGeometry(QtCore.QRect(148, 212, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.G4.sizePolicy().hasHeightForWidth())
        self.G4.setSizePolicy(sizePolicy)
        self.G4.setText("")
        self.G4.setObjectName("G4")
        self.G5 = QtWidgets.QLabel(CreateNewGameDialog)
        self.G5.setGeometry(QtCore.QRect(180, 212, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.G5.sizePolicy().hasHeightForWidth())
        self.G5.setSizePolicy(sizePolicy)
        self.G5.setText("")
        self.G5.setObjectName("G5")
        self.G6 = QtWidgets.QLabel(CreateNewGameDialog)
        self.G6.setGeometry(QtCore.QRect(212, 212, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.G6.sizePolicy().hasHeightForWidth())
        self.G6.setSizePolicy(sizePolicy)
        self.G6.setText("")
        self.G6.setObjectName("G6")
        self.G7 = QtWidgets.QLabel(CreateNewGameDialog)
        self.G7.setGeometry(QtCore.QRect(244, 212, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.G7.sizePolicy().hasHeightForWidth())
        self.G7.setSizePolicy(sizePolicy)
        self.G7.setText("")
        self.G7.setObjectName("G7")
        self.G8 = QtWidgets.QLabel(CreateNewGameDialog)
        self.G8.setGeometry(QtCore.QRect(276, 212, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.G8.sizePolicy().hasHeightForWidth())
        self.G8.setSizePolicy(sizePolicy)
        self.G8.setText("")
        self.G8.setObjectName("G8")
        self.H1 = QtWidgets.QLabel(CreateNewGameDialog)
        self.H1.setGeometry(QtCore.QRect(52, 244, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.H1.sizePolicy().hasHeightForWidth())
        self.H1.setSizePolicy(sizePolicy)
        self.H1.setText("")
        self.H1.setObjectName("H1")
        self.H2 = QtWidgets.QLabel(CreateNewGameDialog)
        self.H2.setGeometry(QtCore.QRect(84, 244, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.H2.sizePolicy().hasHeightForWidth())
        self.H2.setSizePolicy(sizePolicy)
        self.H2.setText("")
        self.H2.setObjectName("H2")
        self.H3 = QtWidgets.QLabel(CreateNewGameDialog)
        self.H3.setGeometry(QtCore.QRect(116, 244, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.H3.sizePolicy().hasHeightForWidth())
        self.H3.setSizePolicy(sizePolicy)
        self.H3.setText("")
        self.H3.setObjectName("H3")
        self.H4 = QtWidgets.QLabel(CreateNewGameDialog)
        self.H4.setGeometry(QtCore.QRect(148, 244, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.H4.sizePolicy().hasHeightForWidth())
        self.H4.setSizePolicy(sizePolicy)
        self.H4.setText("")
        self.H4.setObjectName("H4")
        self.H5 = QtWidgets.QLabel(CreateNewGameDialog)
        self.H5.setGeometry(QtCore.QRect(180, 244, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.H5.sizePolicy().hasHeightForWidth())
        self.H5.setSizePolicy(sizePolicy)
        self.H5.setText("")
        self.H5.setObjectName("H5")
        self.H6 = QtWidgets.QLabel(CreateNewGameDialog)
        self.H6.setGeometry(QtCore.QRect(212, 244, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.H6.sizePolicy().hasHeightForWidth())
        self.H6.setSizePolicy(sizePolicy)
        self.H6.setText("")
        self.H6.setObjectName("H6")
        self.H7 = QtWidgets.QLabel(CreateNewGameDialog)
        self.H7.setGeometry(QtCore.QRect(244, 244, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.H7.sizePolicy().hasHeightForWidth())
        self.H7.setSizePolicy(sizePolicy)
        self.H7.setText("")
        self.H7.setObjectName("H7")
        self.H8 = QtWidgets.QLabel(CreateNewGameDialog)
        self.H8.setGeometry(QtCore.QRect(276, 244, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.H8.sizePolicy().hasHeightForWidth())
        self.H8.setSizePolicy(sizePolicy)
        self.H8.setText("")
        self.H8.setObjectName("H8")

        self.retranslateUi(CreateNewGameDialog)
        self.buttonBox.accepted.connect(CreateNewGameDialog.accept)
        self.buttonBox.rejected.connect(CreateNewGameDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(CreateNewGameDialog)

    def retranslateUi(self, CreateNewGameDialog):
        _translate = QtCore.QCoreApplication.translate
        CreateNewGameDialog.setWindowTitle(_translate("CreateNewGameDialog", "Создать новую игру"))
        self.label_A.setText(_translate("CreateNewGameDialog", "8"))
        self.label_B.setText(_translate("CreateNewGameDialog", "7"))
        self.label_C.setText(_translate("CreateNewGameDialog", "6"))
        self.label_D.setText(_translate("CreateNewGameDialog", "5"))
        self.label_E.setText(_translate("CreateNewGameDialog", "4"))
        self.label_F.setText(_translate("CreateNewGameDialog", "3"))
        self.label_G.setText(_translate("CreateNewGameDialog", "2"))
        self.label_H.setText(_translate("CreateNewGameDialog", "1"))
        self.label_1.setText(_translate("CreateNewGameDialog", "A"))
        self.label_2.setText(_translate("CreateNewGameDialog", "B"))
        self.label_3.setText(_translate("CreateNewGameDialog", "C"))
        self.label_4.setText(_translate("CreateNewGameDialog", "D"))
        self.label_5.setText(_translate("CreateNewGameDialog", "E"))
        self.label_6.setText(_translate("CreateNewGameDialog", "F"))
        self.label_7.setText(_translate("CreateNewGameDialog", "G"))
        self.label_8.setText(_translate("CreateNewGameDialog", "H"))
        self.label_players_1.setText(_translate("CreateNewGameDialog", "Введите имена и выберете"))
        self.label_players_2.setText(_translate("CreateNewGameDialog", "игрока совершающего"))
        self.label_9.setText(_translate("CreateNewGameDialog", "Чёрные фигуры"))
        self.label_players_3.setText(_translate("CreateNewGameDialog", "первый ход:"))
        self.label.setText(_translate("CreateNewGameDialog", "Белые фигуры"))
        self.label_black_or_white.setText(_translate("CreateNewGameDialog", "Белые     Чёрные"))
        self.clear.setText(_translate("CreateNewGameDialog", "Убрать фигуру"))
