# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 620)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 800, 591))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.Game = QtWidgets.QWidget()
        self.Game.setObjectName("Game")
        self.label_C = QtWidgets.QLabel(self.Game)
        self.label_C.setGeometry(QtCore.QRect(20, 140, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_C.sizePolicy().hasHeightForWidth())
        self.label_C.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.label_C.setFont(font)
        self.label_C.setStyleSheet("color: #8e2426;")
        self.label_C.setAlignment(QtCore.Qt.AlignCenter)
        self.label_C.setObjectName("label_C")
        self.label_1 = QtWidgets.QLabel(self.Game)
        self.label_1.setGeometry(QtCore.QRect(80, 500, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_1.sizePolicy().hasHeightForWidth())
        self.label_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.label_1.setFont(font)
        self.label_1.setStyleSheet("color: #8e2426;")
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1.setObjectName("label_1")
        self.label_F = QtWidgets.QLabel(self.Game)
        self.label_F.setGeometry(QtCore.QRect(20, 320, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_F.sizePolicy().hasHeightForWidth())
        self.label_F.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.label_F.setFont(font)
        self.label_F.setStyleSheet("color: #8e2426;")
        self.label_F.setAlignment(QtCore.Qt.AlignCenter)
        self.label_F.setObjectName("label_F")
        self.label_8 = QtWidgets.QLabel(self.Game)
        self.label_8.setGeometry(QtCore.QRect(500, 500, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: #8e2426;")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_3 = QtWidgets.QLabel(self.Game)
        self.label_3.setGeometry(QtCore.QRect(200, 500, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: #8e2426;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_B = QtWidgets.QLabel(self.Game)
        self.label_B.setGeometry(QtCore.QRect(20, 80, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_B.sizePolicy().hasHeightForWidth())
        self.label_B.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.label_B.setFont(font)
        self.label_B.setStyleSheet("color: #8e2426;")
        self.label_B.setAlignment(QtCore.Qt.AlignCenter)
        self.label_B.setObjectName("label_B")
        self.label_6 = QtWidgets.QLabel(self.Game)
        self.label_6.setGeometry(QtCore.QRect(380, 500, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: #8e2426;")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_E = QtWidgets.QLabel(self.Game)
        self.label_E.setGeometry(QtCore.QRect(20, 260, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_E.sizePolicy().hasHeightForWidth())
        self.label_E.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.label_E.setFont(font)
        self.label_E.setStyleSheet("color: #8e2426;")
        self.label_E.setAlignment(QtCore.Qt.AlignCenter)
        self.label_E.setObjectName("label_E")
        self.label_H = QtWidgets.QLabel(self.Game)
        self.label_H.setGeometry(QtCore.QRect(20, 440, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_H.sizePolicy().hasHeightForWidth())
        self.label_H.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.label_H.setFont(font)
        self.label_H.setStyleSheet("color: #8e2426;")
        self.label_H.setAlignment(QtCore.Qt.AlignCenter)
        self.label_H.setObjectName("label_H")
        self.label_D = QtWidgets.QLabel(self.Game)
        self.label_D.setGeometry(QtCore.QRect(20, 200, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_D.sizePolicy().hasHeightForWidth())
        self.label_D.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.label_D.setFont(font)
        self.label_D.setStyleSheet("color: #8e2426;")
        self.label_D.setAlignment(QtCore.Qt.AlignCenter)
        self.label_D.setObjectName("label_D")
        self.label_4 = QtWidgets.QLabel(self.Game)
        self.label_4.setGeometry(QtCore.QRect(260, 500, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: #8e2426;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.A = QtWidgets.QLabel(self.Game)
        self.A.setGeometry(QtCore.QRect(380, 20, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.A.sizePolicy().hasHeightForWidth())
        self.A.setSizePolicy(sizePolicy)
        self.A.setText("")
        self.A.setObjectName("A")
        self.label_G = QtWidgets.QLabel(self.Game)
        self.label_G.setGeometry(QtCore.QRect(20, 380, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_G.sizePolicy().hasHeightForWidth())
        self.label_G.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.label_G.setFont(font)
        self.label_G.setStyleSheet("color: #8e2426;")
        self.label_G.setAlignment(QtCore.Qt.AlignCenter)
        self.label_G.setObjectName("label_G")
        self.label_A = QtWidgets.QLabel(self.Game)
        self.label_A.setGeometry(QtCore.QRect(20, 20, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_A.sizePolicy().hasHeightForWidth())
        self.label_A.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.label_A.setFont(font)
        self.label_A.setStyleSheet("color: #8e2426;")
        self.label_A.setAlignment(QtCore.Qt.AlignCenter)
        self.label_A.setObjectName("label_A")
        self.label_2 = QtWidgets.QLabel(self.Game)
        self.label_2.setGeometry(QtCore.QRect(140, 500, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #8e2426;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_7 = QtWidgets.QLabel(self.Game)
        self.label_7.setGeometry(QtCore.QRect(440, 500, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: #8e2426;")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_5 = QtWidgets.QLabel(self.Game)
        self.label_5.setGeometry(QtCore.QRect(320, 500, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: #8e2426;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.area = QtWidgets.QLabel(self.Game)
        self.area.setGeometry(QtCore.QRect(80, 20, 480, 480))
        self.area.setText("")
        self.area.setObjectName("area")
        self.F8 = QtWidgets.QLabel(self.Game)
        self.F8.setGeometry(QtCore.QRect(500, 320, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.F8.sizePolicy().hasHeightForWidth())
        self.F8.setSizePolicy(sizePolicy)
        self.F8.setText("")
        self.F8.setObjectName("F8")
        self.A7 = QtWidgets.QLabel(self.Game)
        self.A7.setGeometry(QtCore.QRect(440, 20, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.A7.sizePolicy().hasHeightForWidth())
        self.A7.setSizePolicy(sizePolicy)
        self.A7.setText("")
        self.A7.setObjectName("A7")
        self.G1 = QtWidgets.QLabel(self.Game)
        self.G1.setGeometry(QtCore.QRect(80, 380, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.G1.sizePolicy().hasHeightForWidth())
        self.G1.setSizePolicy(sizePolicy)
        self.G1.setText("")
        self.G1.setObjectName("G1")
        self.H7 = QtWidgets.QLabel(self.Game)
        self.H7.setGeometry(QtCore.QRect(440, 440, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.H7.sizePolicy().hasHeightForWidth())
        self.H7.setSizePolicy(sizePolicy)
        self.H7.setText("")
        self.H7.setObjectName("H7")
        self.D4 = QtWidgets.QLabel(self.Game)
        self.D4.setGeometry(QtCore.QRect(260, 200, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D4.sizePolicy().hasHeightForWidth())
        self.D4.setSizePolicy(sizePolicy)
        self.D4.setText("")
        self.D4.setObjectName("D4")
        self.B8 = QtWidgets.QLabel(self.Game)
        self.B8.setGeometry(QtCore.QRect(500, 80, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.B8.sizePolicy().hasHeightForWidth())
        self.B8.setSizePolicy(sizePolicy)
        self.B8.setText("")
        self.B8.setObjectName("B8")
        self.B1 = QtWidgets.QLabel(self.Game)
        self.B1.setGeometry(QtCore.QRect(80, 80, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.B1.sizePolicy().hasHeightForWidth())
        self.B1.setSizePolicy(sizePolicy)
        self.B1.setText("")
        self.B1.setObjectName("B1")
        self.H6 = QtWidgets.QLabel(self.Game)
        self.H6.setGeometry(QtCore.QRect(380, 440, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.H6.sizePolicy().hasHeightForWidth())
        self.H6.setSizePolicy(sizePolicy)
        self.H6.setText("")
        self.H6.setObjectName("H6")
        self.C2 = QtWidgets.QLabel(self.Game)
        self.C2.setGeometry(QtCore.QRect(140, 140, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.C2.sizePolicy().hasHeightForWidth())
        self.C2.setSizePolicy(sizePolicy)
        self.C2.setText("")
        self.C2.setObjectName("C2")
        self.H1 = QtWidgets.QLabel(self.Game)
        self.H1.setGeometry(QtCore.QRect(80, 440, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.H1.sizePolicy().hasHeightForWidth())
        self.H1.setSizePolicy(sizePolicy)
        self.H1.setText("")
        self.H1.setObjectName("H1")
        self.F7 = QtWidgets.QLabel(self.Game)
        self.F7.setGeometry(QtCore.QRect(440, 320, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.F7.sizePolicy().hasHeightForWidth())
        self.F7.setSizePolicy(sizePolicy)
        self.F7.setText("")
        self.F7.setObjectName("F7")
        self.H5 = QtWidgets.QLabel(self.Game)
        self.H5.setGeometry(QtCore.QRect(320, 440, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.H5.sizePolicy().hasHeightForWidth())
        self.H5.setSizePolicy(sizePolicy)
        self.H5.setText("")
        self.H5.setObjectName("H5")
        self.H2 = QtWidgets.QLabel(self.Game)
        self.H2.setGeometry(QtCore.QRect(140, 440, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.H2.sizePolicy().hasHeightForWidth())
        self.H2.setSizePolicy(sizePolicy)
        self.H2.setText("")
        self.H2.setObjectName("H2")
        self.D3 = QtWidgets.QLabel(self.Game)
        self.D3.setGeometry(QtCore.QRect(200, 200, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D3.sizePolicy().hasHeightForWidth())
        self.D3.setSizePolicy(sizePolicy)
        self.D3.setText("")
        self.D3.setObjectName("D3")
        self.C5 = QtWidgets.QLabel(self.Game)
        self.C5.setGeometry(QtCore.QRect(320, 140, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.C5.sizePolicy().hasHeightForWidth())
        self.C5.setSizePolicy(sizePolicy)
        self.C5.setText("")
        self.C5.setObjectName("C5")
        self.F5 = QtWidgets.QLabel(self.Game)
        self.F5.setGeometry(QtCore.QRect(320, 320, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.F5.sizePolicy().hasHeightForWidth())
        self.F5.setSizePolicy(sizePolicy)
        self.F5.setText("")
        self.F5.setObjectName("F5")
        self.G6 = QtWidgets.QLabel(self.Game)
        self.G6.setGeometry(QtCore.QRect(380, 380, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.G6.sizePolicy().hasHeightForWidth())
        self.G6.setSizePolicy(sizePolicy)
        self.G6.setText("")
        self.G6.setObjectName("G6")
        self.B7 = QtWidgets.QLabel(self.Game)
        self.B7.setGeometry(QtCore.QRect(440, 80, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.B7.sizePolicy().hasHeightForWidth())
        self.B7.setSizePolicy(sizePolicy)
        self.B7.setText("")
        self.B7.setObjectName("B7")
        self.B3 = QtWidgets.QLabel(self.Game)
        self.B3.setGeometry(QtCore.QRect(200, 80, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.B3.sizePolicy().hasHeightForWidth())
        self.B3.setSizePolicy(sizePolicy)
        self.B3.setText("")
        self.B3.setObjectName("B3")
        self.C7 = QtWidgets.QLabel(self.Game)
        self.C7.setGeometry(QtCore.QRect(440, 140, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.C7.sizePolicy().hasHeightForWidth())
        self.C7.setSizePolicy(sizePolicy)
        self.C7.setText("")
        self.C7.setObjectName("C7")
        self.A2 = QtWidgets.QLabel(self.Game)
        self.A2.setGeometry(QtCore.QRect(140, 20, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.A2.sizePolicy().hasHeightForWidth())
        self.A2.setSizePolicy(sizePolicy)
        self.A2.setText("")
        self.A2.setObjectName("A2")
        self.A1 = QtWidgets.QLabel(self.Game)
        self.A1.setGeometry(QtCore.QRect(80, 20, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.A1.sizePolicy().hasHeightForWidth())
        self.A1.setSizePolicy(sizePolicy)
        self.A1.setText("")
        self.A1.setObjectName("A1")
        self.G3 = QtWidgets.QLabel(self.Game)
        self.G3.setGeometry(QtCore.QRect(200, 380, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.G3.sizePolicy().hasHeightForWidth())
        self.G3.setSizePolicy(sizePolicy)
        self.G3.setText("")
        self.G3.setObjectName("G3")
        self.A4 = QtWidgets.QLabel(self.Game)
        self.A4.setGeometry(QtCore.QRect(260, 20, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.A4.sizePolicy().hasHeightForWidth())
        self.A4.setSizePolicy(sizePolicy)
        self.A4.setText("")
        self.A4.setObjectName("A4")
        self.E6 = QtWidgets.QLabel(self.Game)
        self.E6.setGeometry(QtCore.QRect(380, 260, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.E6.sizePolicy().hasHeightForWidth())
        self.E6.setSizePolicy(sizePolicy)
        self.E6.setText("")
        self.E6.setObjectName("E6")
        self.H4 = QtWidgets.QLabel(self.Game)
        self.H4.setGeometry(QtCore.QRect(260, 440, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.H4.sizePolicy().hasHeightForWidth())
        self.H4.setSizePolicy(sizePolicy)
        self.H4.setText("")
        self.H4.setObjectName("H4")
        self.E4 = QtWidgets.QLabel(self.Game)
        self.E4.setGeometry(QtCore.QRect(260, 260, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.E4.sizePolicy().hasHeightForWidth())
        self.E4.setSizePolicy(sizePolicy)
        self.E4.setText("")
        self.E4.setObjectName("E4")
        self.H8 = QtWidgets.QLabel(self.Game)
        self.H8.setGeometry(QtCore.QRect(500, 440, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.H8.sizePolicy().hasHeightForWidth())
        self.H8.setSizePolicy(sizePolicy)
        self.H8.setText("")
        self.H8.setObjectName("H8")
        self.C6 = QtWidgets.QLabel(self.Game)
        self.C6.setGeometry(QtCore.QRect(380, 140, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.C6.sizePolicy().hasHeightForWidth())
        self.C6.setSizePolicy(sizePolicy)
        self.C6.setText("")
        self.C6.setObjectName("C6")
        self.D1 = QtWidgets.QLabel(self.Game)
        self.D1.setGeometry(QtCore.QRect(80, 200, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D1.sizePolicy().hasHeightForWidth())
        self.D1.setSizePolicy(sizePolicy)
        self.D1.setText("")
        self.D1.setObjectName("D1")
        self.B4 = QtWidgets.QLabel(self.Game)
        self.B4.setGeometry(QtCore.QRect(260, 80, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.B4.sizePolicy().hasHeightForWidth())
        self.B4.setSizePolicy(sizePolicy)
        self.B4.setText("")
        self.B4.setObjectName("B4")
        self.E8 = QtWidgets.QLabel(self.Game)
        self.E8.setGeometry(QtCore.QRect(500, 260, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.E8.sizePolicy().hasHeightForWidth())
        self.E8.setSizePolicy(sizePolicy)
        self.E8.setText("")
        self.E8.setObjectName("E8")
        self.F3 = QtWidgets.QLabel(self.Game)
        self.F3.setGeometry(QtCore.QRect(200, 320, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.F3.sizePolicy().hasHeightForWidth())
        self.F3.setSizePolicy(sizePolicy)
        self.F3.setText("")
        self.F3.setObjectName("F3")
        self.B6 = QtWidgets.QLabel(self.Game)
        self.B6.setGeometry(QtCore.QRect(380, 80, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.B6.sizePolicy().hasHeightForWidth())
        self.B6.setSizePolicy(sizePolicy)
        self.B6.setText("")
        self.B6.setObjectName("B6")
        self.C3 = QtWidgets.QLabel(self.Game)
        self.C3.setGeometry(QtCore.QRect(200, 140, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.C3.sizePolicy().hasHeightForWidth())
        self.C3.setSizePolicy(sizePolicy)
        self.C3.setText("")
        self.C3.setObjectName("C3")
        self.E3 = QtWidgets.QLabel(self.Game)
        self.E3.setGeometry(QtCore.QRect(200, 260, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.E3.sizePolicy().hasHeightForWidth())
        self.E3.setSizePolicy(sizePolicy)
        self.E3.setText("")
        self.E3.setObjectName("E3")
        self.C8 = QtWidgets.QLabel(self.Game)
        self.C8.setGeometry(QtCore.QRect(500, 140, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.C8.sizePolicy().hasHeightForWidth())
        self.C8.setSizePolicy(sizePolicy)
        self.C8.setText("")
        self.C8.setObjectName("C8")
        self.E2 = QtWidgets.QLabel(self.Game)
        self.E2.setGeometry(QtCore.QRect(140, 260, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.E2.sizePolicy().hasHeightForWidth())
        self.E2.setSizePolicy(sizePolicy)
        self.E2.setText("")
        self.E2.setObjectName("E2")
        self.F6 = QtWidgets.QLabel(self.Game)
        self.F6.setGeometry(QtCore.QRect(380, 320, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.F6.sizePolicy().hasHeightForWidth())
        self.F6.setSizePolicy(sizePolicy)
        self.F6.setText("")
        self.F6.setObjectName("F6")
        self.G7 = QtWidgets.QLabel(self.Game)
        self.G7.setGeometry(QtCore.QRect(440, 380, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.G7.sizePolicy().hasHeightForWidth())
        self.G7.setSizePolicy(sizePolicy)
        self.G7.setText("")
        self.G7.setObjectName("G7")
        self.E5 = QtWidgets.QLabel(self.Game)
        self.E5.setGeometry(QtCore.QRect(320, 260, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.E5.sizePolicy().hasHeightForWidth())
        self.E5.setSizePolicy(sizePolicy)
        self.E5.setText("")
        self.E5.setObjectName("E5")
        self.D7 = QtWidgets.QLabel(self.Game)
        self.D7.setGeometry(QtCore.QRect(440, 200, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D7.sizePolicy().hasHeightForWidth())
        self.D7.setSizePolicy(sizePolicy)
        self.D7.setText("")
        self.D7.setObjectName("D7")
        self.C4 = QtWidgets.QLabel(self.Game)
        self.C4.setGeometry(QtCore.QRect(260, 140, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.C4.sizePolicy().hasHeightForWidth())
        self.C4.setSizePolicy(sizePolicy)
        self.C4.setText("")
        self.C4.setObjectName("C4")
        self.E7 = QtWidgets.QLabel(self.Game)
        self.E7.setGeometry(QtCore.QRect(440, 260, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.E7.sizePolicy().hasHeightForWidth())
        self.E7.setSizePolicy(sizePolicy)
        self.E7.setText("")
        self.E7.setObjectName("E7")
        self.H3 = QtWidgets.QLabel(self.Game)
        self.H3.setGeometry(QtCore.QRect(200, 440, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.H3.sizePolicy().hasHeightForWidth())
        self.H3.setSizePolicy(sizePolicy)
        self.H3.setText("")
        self.H3.setObjectName("H3")
        self.D6 = QtWidgets.QLabel(self.Game)
        self.D6.setGeometry(QtCore.QRect(380, 200, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D6.sizePolicy().hasHeightForWidth())
        self.D6.setSizePolicy(sizePolicy)
        self.D6.setText("")
        self.D6.setObjectName("D6")
        self.G5 = QtWidgets.QLabel(self.Game)
        self.G5.setGeometry(QtCore.QRect(320, 380, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.G5.sizePolicy().hasHeightForWidth())
        self.G5.setSizePolicy(sizePolicy)
        self.G5.setText("")
        self.G5.setObjectName("G5")
        self.G2 = QtWidgets.QLabel(self.Game)
        self.G2.setGeometry(QtCore.QRect(140, 380, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.G2.sizePolicy().hasHeightForWidth())
        self.G2.setSizePolicy(sizePolicy)
        self.G2.setText("")
        self.G2.setObjectName("G2")
        self.F4 = QtWidgets.QLabel(self.Game)
        self.F4.setGeometry(QtCore.QRect(260, 320, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.F4.sizePolicy().hasHeightForWidth())
        self.F4.setSizePolicy(sizePolicy)
        self.F4.setText("")
        self.F4.setObjectName("F4")
        self.D5 = QtWidgets.QLabel(self.Game)
        self.D5.setGeometry(QtCore.QRect(320, 200, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D5.sizePolicy().hasHeightForWidth())
        self.D5.setSizePolicy(sizePolicy)
        self.D5.setText("")
        self.D5.setObjectName("D5")
        self.G4 = QtWidgets.QLabel(self.Game)
        self.G4.setGeometry(QtCore.QRect(260, 380, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.G4.sizePolicy().hasHeightForWidth())
        self.G4.setSizePolicy(sizePolicy)
        self.G4.setText("")
        self.G4.setObjectName("G4")
        self.E1 = QtWidgets.QLabel(self.Game)
        self.E1.setGeometry(QtCore.QRect(80, 260, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.E1.sizePolicy().hasHeightForWidth())
        self.E1.setSizePolicy(sizePolicy)
        self.E1.setText("")
        self.E1.setObjectName("E1")
        self.D2 = QtWidgets.QLabel(self.Game)
        self.D2.setGeometry(QtCore.QRect(140, 200, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D2.sizePolicy().hasHeightForWidth())
        self.D2.setSizePolicy(sizePolicy)
        self.D2.setText("")
        self.D2.setObjectName("D2")
        self.F2 = QtWidgets.QLabel(self.Game)
        self.F2.setGeometry(QtCore.QRect(140, 320, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.F2.sizePolicy().hasHeightForWidth())
        self.F2.setSizePolicy(sizePolicy)
        self.F2.setText("")
        self.F2.setObjectName("F2")
        self.F1 = QtWidgets.QLabel(self.Game)
        self.F1.setGeometry(QtCore.QRect(80, 320, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.F1.sizePolicy().hasHeightForWidth())
        self.F1.setSizePolicy(sizePolicy)
        self.F1.setText("")
        self.F1.setObjectName("F1")
        self.B5 = QtWidgets.QLabel(self.Game)
        self.B5.setGeometry(QtCore.QRect(320, 80, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.B5.sizePolicy().hasHeightForWidth())
        self.B5.setSizePolicy(sizePolicy)
        self.B5.setText("")
        self.B5.setObjectName("B5")
        self.A5 = QtWidgets.QLabel(self.Game)
        self.A5.setGeometry(QtCore.QRect(320, 20, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.A5.sizePolicy().hasHeightForWidth())
        self.A5.setSizePolicy(sizePolicy)
        self.A5.setText("")
        self.A5.setObjectName("A5")
        self.G8 = QtWidgets.QLabel(self.Game)
        self.G8.setGeometry(QtCore.QRect(500, 380, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.G8.sizePolicy().hasHeightForWidth())
        self.G8.setSizePolicy(sizePolicy)
        self.G8.setText("")
        self.G8.setObjectName("G8")
        self.D8 = QtWidgets.QLabel(self.Game)
        self.D8.setGeometry(QtCore.QRect(500, 200, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D8.sizePolicy().hasHeightForWidth())
        self.D8.setSizePolicy(sizePolicy)
        self.D8.setText("")
        self.D8.setObjectName("D8")
        self.A8 = QtWidgets.QLabel(self.Game)
        self.A8.setGeometry(QtCore.QRect(500, 20, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.A8.sizePolicy().hasHeightForWidth())
        self.A8.setSizePolicy(sizePolicy)
        self.A8.setText("")
        self.A8.setObjectName("A8")
        self.A3 = QtWidgets.QLabel(self.Game)
        self.A3.setGeometry(QtCore.QRect(200, 20, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.A3.sizePolicy().hasHeightForWidth())
        self.A3.setSizePolicy(sizePolicy)
        self.A3.setText("")
        self.A3.setObjectName("A3")
        self.C1 = QtWidgets.QLabel(self.Game)
        self.C1.setGeometry(QtCore.QRect(80, 140, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.C1.sizePolicy().hasHeightForWidth())
        self.C1.setSizePolicy(sizePolicy)
        self.C1.setText("")
        self.C1.setObjectName("C1")
        self.B2 = QtWidgets.QLabel(self.Game)
        self.B2.setGeometry(QtCore.QRect(140, 80, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.B2.sizePolicy().hasHeightForWidth())
        self.B2.setSizePolicy(sizePolicy)
        self.B2.setText("")
        self.B2.setObjectName("B2")
        self.A6 = QtWidgets.QLabel(self.Game)
        self.A6.setGeometry(QtCore.QRect(380, 20, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.A6.sizePolicy().hasHeightForWidth())
        self.A6.setSizePolicy(sizePolicy)
        self.A6.setText("")
        self.A6.setObjectName("A6")
        self.line = QtWidgets.QFrame(self.Game)
        self.line.setGeometry(QtCore.QRect(560, 0, 20, 561))
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.leave = QtWidgets.QPushButton(self.Game)
        self.leave.setGeometry(QtCore.QRect(600, 530, 71, 23))
        self.leave.setObjectName("leave")
        self.exit = QtWidgets.QPushButton(self.Game)
        self.exit.setGeometry(QtCore.QRect(690, 530, 71, 23))
        self.exit.setObjectName("exit")
        self.choose_piece_text = QtWidgets.QLabel(self.Game)
        self.choose_piece_text.setGeometry(QtCore.QRect(600, 5, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.choose_piece_text.setFont(font)
        self.choose_piece_text.setAlignment(QtCore.Qt.AlignCenter)
        self.choose_piece_text.setObjectName("choose_piece_text")
        self.line_2 = QtWidgets.QFrame(self.Game)
        self.line_2.setGeometry(QtCore.QRect(570, 40, 221, 16))
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.Game)
        self.line_3.setGeometry(QtCore.QRect(570, 470, 221, 16))
        self.line_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_3.setLineWidth(2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setObjectName("line_3")
        self.list_moves = QtWidgets.QListWidget(self.Game)
        self.list_moves.setGeometry(QtCore.QRect(580, 150, 201, 311))
        self.list_moves.setObjectName("list_moves")
        self.label_9 = QtWidgets.QLabel(self.Game)
        self.label_9.setGeometry(QtCore.QRect(580, 110, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.line_7 = QtWidgets.QFrame(self.Game)
        self.line_7.setGeometry(QtCore.QRect(570, 90, 221, 16))
        self.line_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_7.setLineWidth(2)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setObjectName("line_7")
        self.player_move = QtWidgets.QLabel(self.Game)
        self.player_move.setGeometry(QtCore.QRect(570, 50, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.player_move.setFont(font)
        self.player_move.setAlignment(QtCore.Qt.AlignCenter)
        self.player_move.setObjectName("player_move")
        self.return_to_menu = QtWidgets.QPushButton(self.Game)
        self.return_to_menu.setGeometry(QtCore.QRect(600, 490, 161, 23))
        self.return_to_menu.setObjectName("return_to_menu")
        self.tabWidget.addTab(self.Game, "")
        self.History = QtWidgets.QWidget()
        self.History.setObjectName("History")
        self.B6_2 = QtWidgets.QLabel(self.History)
        self.B6_2.setGeometry(QtCore.QRect(380, 80, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.B6_2.sizePolicy().hasHeightForWidth())
        self.B6_2.setSizePolicy(sizePolicy)
        self.B6_2.setText("")
        self.B6_2.setObjectName("B6_2")
        self.B7_2 = QtWidgets.QLabel(self.History)
        self.B7_2.setGeometry(QtCore.QRect(440, 80, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.B7_2.sizePolicy().hasHeightForWidth())
        self.B7_2.setSizePolicy(sizePolicy)
        self.B7_2.setText("")
        self.B7_2.setObjectName("B7_2")
        self.label_H_2 = QtWidgets.QLabel(self.History)
        self.label_H_2.setGeometry(QtCore.QRect(20, 440, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_H_2.sizePolicy().hasHeightForWidth())
        self.label_H_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.label_H_2.setFont(font)
        self.label_H_2.setStyleSheet("color: #8e2426;")
        self.label_H_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_H_2.setObjectName("label_H_2")
        self.A5_2 = QtWidgets.QLabel(self.History)
        self.A5_2.setGeometry(QtCore.QRect(320, 20, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.A5_2.sizePolicy().hasHeightForWidth())
        self.A5_2.setSizePolicy(sizePolicy)
        self.A5_2.setText("")
        self.A5_2.setObjectName("A5_2")
        self.E1_2 = QtWidgets.QLabel(self.History)
        self.E1_2.setGeometry(QtCore.QRect(80, 260, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.E1_2.sizePolicy().hasHeightForWidth())
        self.E1_2.setSizePolicy(sizePolicy)
        self.E1_2.setText("")
        self.E1_2.setObjectName("E1_2")
        self.B2_2 = QtWidgets.QLabel(self.History)
        self.B2_2.setGeometry(QtCore.QRect(140, 80, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.B2_2.sizePolicy().hasHeightForWidth())
        self.B2_2.setSizePolicy(sizePolicy)
        self.B2_2.setText("")
        self.B2_2.setObjectName("B2_2")
        self.H4_2 = QtWidgets.QLabel(self.History)
        self.H4_2.setGeometry(QtCore.QRect(260, 440, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.H4_2.sizePolicy().hasHeightForWidth())
        self.H4_2.setSizePolicy(sizePolicy)
        self.H4_2.setText("")
        self.H4_2.setObjectName("H4_2")
        self.H8_2 = QtWidgets.QLabel(self.History)
        self.H8_2.setGeometry(QtCore.QRect(500, 440, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.H8_2.sizePolicy().hasHeightForWidth())
        self.H8_2.setSizePolicy(sizePolicy)
        self.H8_2.setText("")
        self.H8_2.setObjectName("H8_2")
        self.label_10 = QtWidgets.QLabel(self.History)
        self.label_10.setGeometry(QtCore.QRect(320, 500, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: #8e2426;")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.F6_2 = QtWidgets.QLabel(self.History)
        self.F6_2.setGeometry(QtCore.QRect(380, 320, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.F6_2.sizePolicy().hasHeightForWidth())
        self.F6_2.setSizePolicy(sizePolicy)
        self.F6_2.setText("")
        self.F6_2.setObjectName("F6_2")
        self.A8_2 = QtWidgets.QLabel(self.History)
        self.A8_2.setGeometry(QtCore.QRect(500, 20, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.A8_2.sizePolicy().hasHeightForWidth())
        self.A8_2.setSizePolicy(sizePolicy)
        self.A8_2.setText("")
        self.A8_2.setObjectName("A8_2")
        self.D6_2 = QtWidgets.QLabel(self.History)
        self.D6_2.setGeometry(QtCore.QRect(380, 200, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D6_2.sizePolicy().hasHeightForWidth())
        self.D6_2.setSizePolicy(sizePolicy)
        self.D6_2.setText("")
        self.D6_2.setObjectName("D6_2")
        self.label_B_2 = QtWidgets.QLabel(self.History)
        self.label_B_2.setGeometry(QtCore.QRect(20, 80, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_B_2.sizePolicy().hasHeightForWidth())
        self.label_B_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.label_B_2.setFont(font)
        self.label_B_2.setStyleSheet("color: #8e2426;")
        self.label_B_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_B_2.setObjectName("label_B_2")
        self.H1_2 = QtWidgets.QLabel(self.History)
        self.H1_2.setGeometry(QtCore.QRect(80, 440, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.H1_2.sizePolicy().hasHeightForWidth())
        self.H1_2.setSizePolicy(sizePolicy)
        self.H1_2.setText("")
        self.H1_2.setObjectName("H1_2")
        self.E8_2 = QtWidgets.QLabel(self.History)
        self.E8_2.setGeometry(QtCore.QRect(500, 260, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.E8_2.sizePolicy().hasHeightForWidth())
        self.E8_2.setSizePolicy(sizePolicy)
        self.E8_2.setText("")
        self.E8_2.setObjectName("E8_2")
        self.E5_2 = QtWidgets.QLabel(self.History)
        self.E5_2.setGeometry(QtCore.QRect(320, 260, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.E5_2.sizePolicy().hasHeightForWidth())
        self.E5_2.setSizePolicy(sizePolicy)
        self.E5_2.setText("")
        self.E5_2.setObjectName("E5_2")
        self.label_11 = QtWidgets.QLabel(self.History)
        self.label_11.setGeometry(QtCore.QRect(380, 500, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: #8e2426;")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.D7_2 = QtWidgets.QLabel(self.History)
        self.D7_2.setGeometry(QtCore.QRect(440, 200, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D7_2.sizePolicy().hasHeightForWidth())
        self.D7_2.setSizePolicy(sizePolicy)
        self.D7_2.setText("")
        self.D7_2.setObjectName("D7_2")
        self.A6_2 = QtWidgets.QLabel(self.History)
        self.A6_2.setGeometry(QtCore.QRect(380, 20, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.A6_2.sizePolicy().hasHeightForWidth())
        self.A6_2.setSizePolicy(sizePolicy)
        self.A6_2.setText("")
        self.A6_2.setObjectName("A6_2")
        self.F1_2 = QtWidgets.QLabel(self.History)
        self.F1_2.setGeometry(QtCore.QRect(80, 320, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.F1_2.sizePolicy().hasHeightForWidth())
        self.F1_2.setSizePolicy(sizePolicy)
        self.F1_2.setText("")
        self.F1_2.setObjectName("F1_2")
        self.B5_2 = QtWidgets.QLabel(self.History)
        self.B5_2.setGeometry(QtCore.QRect(320, 80, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.B5_2.sizePolicy().hasHeightForWidth())
        self.B5_2.setSizePolicy(sizePolicy)
        self.B5_2.setText("")
        self.B5_2.setObjectName("B5_2")
        self.A3_2 = QtWidgets.QLabel(self.History)
        self.A3_2.setGeometry(QtCore.QRect(200, 20, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.A3_2.sizePolicy().hasHeightForWidth())
        self.A3_2.setSizePolicy(sizePolicy)
        self.A3_2.setText("")
        self.A3_2.setObjectName("A3_2")
        self.A7_2 = QtWidgets.QLabel(self.History)
        self.A7_2.setGeometry(QtCore.QRect(440, 20, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.A7_2.sizePolicy().hasHeightForWidth())
        self.A7_2.setSizePolicy(sizePolicy)
        self.A7_2.setText("")
        self.A7_2.setObjectName("A7_2")
        self.G5_2 = QtWidgets.QLabel(self.History)
        self.G5_2.setGeometry(QtCore.QRect(320, 380, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.G5_2.sizePolicy().hasHeightForWidth())
        self.G5_2.setSizePolicy(sizePolicy)
        self.G5_2.setText("")
        self.G5_2.setObjectName("G5_2")
        self.F3_2 = QtWidgets.QLabel(self.History)
        self.F3_2.setGeometry(QtCore.QRect(200, 320, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.F3_2.sizePolicy().hasHeightForWidth())
        self.F3_2.setSizePolicy(sizePolicy)
        self.F3_2.setText("")
        self.F3_2.setObjectName("F3_2")
        self.D4_2 = QtWidgets.QLabel(self.History)
        self.D4_2.setGeometry(QtCore.QRect(260, 200, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D4_2.sizePolicy().hasHeightForWidth())
        self.D4_2.setSizePolicy(sizePolicy)
        self.D4_2.setText("")
        self.D4_2.setObjectName("D4_2")
        self.label_12 = QtWidgets.QLabel(self.History)
        self.label_12.setGeometry(QtCore.QRect(200, 500, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: #8e2426;")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.C4_2 = QtWidgets.QLabel(self.History)
        self.C4_2.setGeometry(QtCore.QRect(260, 140, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.C4_2.sizePolicy().hasHeightForWidth())
        self.C4_2.setSizePolicy(sizePolicy)
        self.C4_2.setText("")
        self.C4_2.setObjectName("C4_2")
        self.C5_2 = QtWidgets.QLabel(self.History)
        self.C5_2.setGeometry(QtCore.QRect(320, 140, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.C5_2.sizePolicy().hasHeightForWidth())
        self.C5_2.setSizePolicy(sizePolicy)
        self.C5_2.setText("")
        self.C5_2.setObjectName("C5_2")
        self.label_13 = QtWidgets.QLabel(self.History)
        self.label_13.setGeometry(QtCore.QRect(80, 500, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: #8e2426;")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.H3_2 = QtWidgets.QLabel(self.History)
        self.H3_2.setGeometry(QtCore.QRect(200, 440, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.H3_2.sizePolicy().hasHeightForWidth())
        self.H3_2.setSizePolicy(sizePolicy)
        self.H3_2.setText("")
        self.H3_2.setObjectName("H3_2")
        self.label_F_2 = QtWidgets.QLabel(self.History)
        self.label_F_2.setGeometry(QtCore.QRect(20, 320, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_F_2.sizePolicy().hasHeightForWidth())
        self.label_F_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.label_F_2.setFont(font)
        self.label_F_2.setStyleSheet("color: #8e2426;")
        self.label_F_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_F_2.setObjectName("label_F_2")
        self.C3_2 = QtWidgets.QLabel(self.History)
        self.C3_2.setGeometry(QtCore.QRect(200, 140, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.C3_2.sizePolicy().hasHeightForWidth())
        self.C3_2.setSizePolicy(sizePolicy)
        self.C3_2.setText("")
        self.C3_2.setObjectName("C3_2")
        self.F8_2 = QtWidgets.QLabel(self.History)
        self.F8_2.setGeometry(QtCore.QRect(500, 320, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.F8_2.sizePolicy().hasHeightForWidth())
        self.F8_2.setSizePolicy(sizePolicy)
        self.F8_2.setText("")
        self.F8_2.setObjectName("F8_2")
        self.G7_2 = QtWidgets.QLabel(self.History)
        self.G7_2.setGeometry(QtCore.QRect(440, 380, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.G7_2.sizePolicy().hasHeightForWidth())
        self.G7_2.setSizePolicy(sizePolicy)
        self.G7_2.setText("")
        self.G7_2.setObjectName("G7_2")
        self.label_14 = QtWidgets.QLabel(self.History)
        self.label_14.setGeometry(QtCore.QRect(500, 500, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: #8e2426;")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.A2_2 = QtWidgets.QLabel(self.History)
        self.A2_2.setGeometry(QtCore.QRect(140, 20, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.A2_2.sizePolicy().hasHeightForWidth())
        self.A2_2.setSizePolicy(sizePolicy)
        self.A2_2.setText("")
        self.A2_2.setObjectName("A2_2")
        self.A4_2 = QtWidgets.QLabel(self.History)
        self.A4_2.setGeometry(QtCore.QRect(260, 20, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.A4_2.sizePolicy().hasHeightForWidth())
        self.A4_2.setSizePolicy(sizePolicy)
        self.A4_2.setText("")
        self.A4_2.setObjectName("A4_2")
        self.H5_2 = QtWidgets.QLabel(self.History)
        self.H5_2.setGeometry(QtCore.QRect(320, 440, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.H5_2.sizePolicy().hasHeightForWidth())
        self.H5_2.setSizePolicy(sizePolicy)
        self.H5_2.setText("")
        self.H5_2.setObjectName("H5_2")
        self.D1_2 = QtWidgets.QLabel(self.History)
        self.D1_2.setGeometry(QtCore.QRect(80, 200, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D1_2.sizePolicy().hasHeightForWidth())
        self.D1_2.setSizePolicy(sizePolicy)
        self.D1_2.setText("")
        self.D1_2.setObjectName("D1_2")
        self.B4_2 = QtWidgets.QLabel(self.History)
        self.B4_2.setGeometry(QtCore.QRect(260, 80, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.B4_2.sizePolicy().hasHeightForWidth())
        self.B4_2.setSizePolicy(sizePolicy)
        self.B4_2.setText("")
        self.B4_2.setObjectName("B4_2")
        self.C6_2 = QtWidgets.QLabel(self.History)
        self.C6_2.setGeometry(QtCore.QRect(380, 140, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.C6_2.sizePolicy().hasHeightForWidth())
        self.C6_2.setSizePolicy(sizePolicy)
        self.C6_2.setText("")
        self.C6_2.setObjectName("C6_2")
        self.F4_2 = QtWidgets.QLabel(self.History)
        self.F4_2.setGeometry(QtCore.QRect(260, 320, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.F4_2.sizePolicy().hasHeightForWidth())
        self.F4_2.setSizePolicy(sizePolicy)
        self.F4_2.setText("")
        self.F4_2.setObjectName("F4_2")
        self.D8_2 = QtWidgets.QLabel(self.History)
        self.D8_2.setGeometry(QtCore.QRect(500, 200, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D8_2.sizePolicy().hasHeightForWidth())
        self.D8_2.setSizePolicy(sizePolicy)
        self.D8_2.setText("")
        self.D8_2.setObjectName("D8_2")
        self.B3_2 = QtWidgets.QLabel(self.History)
        self.B3_2.setGeometry(QtCore.QRect(200, 80, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.B3_2.sizePolicy().hasHeightForWidth())
        self.B3_2.setSizePolicy(sizePolicy)
        self.B3_2.setText("")
        self.B3_2.setObjectName("B3_2")
        self.H6_2 = QtWidgets.QLabel(self.History)
        self.H6_2.setGeometry(QtCore.QRect(380, 440, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.H6_2.sizePolicy().hasHeightForWidth())
        self.H6_2.setSizePolicy(sizePolicy)
        self.H6_2.setText("")
        self.H6_2.setObjectName("H6_2")
        self.B1_2 = QtWidgets.QLabel(self.History)
        self.B1_2.setGeometry(QtCore.QRect(80, 80, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.B1_2.sizePolicy().hasHeightForWidth())
        self.B1_2.setSizePolicy(sizePolicy)
        self.B1_2.setText("")
        self.B1_2.setObjectName("B1_2")
        self.F7_2 = QtWidgets.QLabel(self.History)
        self.F7_2.setGeometry(QtCore.QRect(440, 320, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.F7_2.sizePolicy().hasHeightForWidth())
        self.F7_2.setSizePolicy(sizePolicy)
        self.F7_2.setText("")
        self.F7_2.setObjectName("F7_2")
        self.H7_2 = QtWidgets.QLabel(self.History)
        self.H7_2.setGeometry(QtCore.QRect(440, 440, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.H7_2.sizePolicy().hasHeightForWidth())
        self.H7_2.setSizePolicy(sizePolicy)
        self.H7_2.setText("")
        self.H7_2.setObjectName("H7_2")
        self.F5_2 = QtWidgets.QLabel(self.History)
        self.F5_2.setGeometry(QtCore.QRect(320, 320, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.F5_2.sizePolicy().hasHeightForWidth())
        self.F5_2.setSizePolicy(sizePolicy)
        self.F5_2.setText("")
        self.F5_2.setObjectName("F5_2")
        self.A1_2 = QtWidgets.QLabel(self.History)
        self.A1_2.setGeometry(QtCore.QRect(80, 20, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.A1_2.sizePolicy().hasHeightForWidth())
        self.A1_2.setSizePolicy(sizePolicy)
        self.A1_2.setText("")
        self.A1_2.setObjectName("A1_2")
        self.label_15 = QtWidgets.QLabel(self.History)
        self.label_15.setGeometry(QtCore.QRect(440, 500, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: #8e2426;")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.label_A_2 = QtWidgets.QLabel(self.History)
        self.label_A_2.setGeometry(QtCore.QRect(20, 20, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_A_2.sizePolicy().hasHeightForWidth())
        self.label_A_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.label_A_2.setFont(font)
        self.label_A_2.setStyleSheet("color: #8e2426;")
        self.label_A_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_A_2.setObjectName("label_A_2")
        self.D3_2 = QtWidgets.QLabel(self.History)
        self.D3_2.setGeometry(QtCore.QRect(200, 200, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D3_2.sizePolicy().hasHeightForWidth())
        self.D3_2.setSizePolicy(sizePolicy)
        self.D3_2.setText("")
        self.D3_2.setObjectName("D3_2")
        self.label_E_2 = QtWidgets.QLabel(self.History)
        self.label_E_2.setGeometry(QtCore.QRect(20, 260, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_E_2.sizePolicy().hasHeightForWidth())
        self.label_E_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.label_E_2.setFont(font)
        self.label_E_2.setStyleSheet("color: #8e2426;")
        self.label_E_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_E_2.setObjectName("label_E_2")
        self.D5_2 = QtWidgets.QLabel(self.History)
        self.D5_2.setGeometry(QtCore.QRect(320, 200, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D5_2.sizePolicy().hasHeightForWidth())
        self.D5_2.setSizePolicy(sizePolicy)
        self.D5_2.setText("")
        self.D5_2.setObjectName("D5_2")
        self.G6_2 = QtWidgets.QLabel(self.History)
        self.G6_2.setGeometry(QtCore.QRect(380, 380, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.G6_2.sizePolicy().hasHeightForWidth())
        self.G6_2.setSizePolicy(sizePolicy)
        self.G6_2.setText("")
        self.G6_2.setObjectName("G6_2")
        self.label_G_2 = QtWidgets.QLabel(self.History)
        self.label_G_2.setGeometry(QtCore.QRect(20, 380, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_G_2.sizePolicy().hasHeightForWidth())
        self.label_G_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.label_G_2.setFont(font)
        self.label_G_2.setStyleSheet("color: #8e2426;")
        self.label_G_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_G_2.setObjectName("label_G_2")
        self.G8_2 = QtWidgets.QLabel(self.History)
        self.G8_2.setGeometry(QtCore.QRect(500, 380, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.G8_2.sizePolicy().hasHeightForWidth())
        self.G8_2.setSizePolicy(sizePolicy)
        self.G8_2.setText("")
        self.G8_2.setObjectName("G8_2")
        self.label_C_2 = QtWidgets.QLabel(self.History)
        self.label_C_2.setGeometry(QtCore.QRect(20, 140, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_C_2.sizePolicy().hasHeightForWidth())
        self.label_C_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.label_C_2.setFont(font)
        self.label_C_2.setStyleSheet("color: #8e2426;")
        self.label_C_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_C_2.setObjectName("label_C_2")
        self.B8_2 = QtWidgets.QLabel(self.History)
        self.B8_2.setGeometry(QtCore.QRect(500, 80, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.B8_2.sizePolicy().hasHeightForWidth())
        self.B8_2.setSizePolicy(sizePolicy)
        self.B8_2.setText("")
        self.B8_2.setObjectName("B8_2")
        self.E7_2 = QtWidgets.QLabel(self.History)
        self.E7_2.setGeometry(QtCore.QRect(440, 260, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.E7_2.sizePolicy().hasHeightForWidth())
        self.E7_2.setSizePolicy(sizePolicy)
        self.E7_2.setText("")
        self.E7_2.setObjectName("E7_2")
        self.area_2 = QtWidgets.QLabel(self.History)
        self.area_2.setGeometry(QtCore.QRect(80, 20, 480, 480))
        self.area_2.setText("")
        self.area_2.setObjectName("area_2")
        self.label_D_2 = QtWidgets.QLabel(self.History)
        self.label_D_2.setGeometry(QtCore.QRect(20, 200, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_D_2.sizePolicy().hasHeightForWidth())
        self.label_D_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.label_D_2.setFont(font)
        self.label_D_2.setStyleSheet("color: #8e2426;")
        self.label_D_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_D_2.setObjectName("label_D_2")
        self.C8_2 = QtWidgets.QLabel(self.History)
        self.C8_2.setGeometry(QtCore.QRect(500, 140, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.C8_2.sizePolicy().hasHeightForWidth())
        self.C8_2.setSizePolicy(sizePolicy)
        self.C8_2.setText("")
        self.C8_2.setObjectName("C8_2")
        self.E3_2 = QtWidgets.QLabel(self.History)
        self.E3_2.setGeometry(QtCore.QRect(200, 260, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.E3_2.sizePolicy().hasHeightForWidth())
        self.E3_2.setSizePolicy(sizePolicy)
        self.E3_2.setText("")
        self.E3_2.setObjectName("E3_2")
        self.label_16 = QtWidgets.QLabel(self.History)
        self.label_16.setGeometry(QtCore.QRect(260, 500, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: #8e2426;")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.E6_2 = QtWidgets.QLabel(self.History)
        self.E6_2.setGeometry(QtCore.QRect(380, 260, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.E6_2.sizePolicy().hasHeightForWidth())
        self.E6_2.setSizePolicy(sizePolicy)
        self.E6_2.setText("")
        self.E6_2.setObjectName("E6_2")
        self.G1_2 = QtWidgets.QLabel(self.History)
        self.G1_2.setGeometry(QtCore.QRect(80, 380, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.G1_2.sizePolicy().hasHeightForWidth())
        self.G1_2.setSizePolicy(sizePolicy)
        self.G1_2.setText("")
        self.G1_2.setObjectName("G1_2")
        self.E4_2 = QtWidgets.QLabel(self.History)
        self.E4_2.setGeometry(QtCore.QRect(260, 260, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.E4_2.sizePolicy().hasHeightForWidth())
        self.E4_2.setSizePolicy(sizePolicy)
        self.E4_2.setText("")
        self.E4_2.setObjectName("E4_2")
        self.F2_2 = QtWidgets.QLabel(self.History)
        self.F2_2.setGeometry(QtCore.QRect(140, 320, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.F2_2.sizePolicy().hasHeightForWidth())
        self.F2_2.setSizePolicy(sizePolicy)
        self.F2_2.setText("")
        self.F2_2.setObjectName("F2_2")
        self.A_2 = QtWidgets.QLabel(self.History)
        self.A_2.setGeometry(QtCore.QRect(380, 20, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.A_2.sizePolicy().hasHeightForWidth())
        self.A_2.setSizePolicy(sizePolicy)
        self.A_2.setText("")
        self.A_2.setObjectName("A_2")
        self.E2_2 = QtWidgets.QLabel(self.History)
        self.E2_2.setGeometry(QtCore.QRect(140, 260, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.E2_2.sizePolicy().hasHeightForWidth())
        self.E2_2.setSizePolicy(sizePolicy)
        self.E2_2.setText("")
        self.E2_2.setObjectName("E2_2")
        self.G3_2 = QtWidgets.QLabel(self.History)
        self.G3_2.setGeometry(QtCore.QRect(200, 380, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.G3_2.sizePolicy().hasHeightForWidth())
        self.G3_2.setSizePolicy(sizePolicy)
        self.G3_2.setText("")
        self.G3_2.setObjectName("G3_2")
        self.H2_2 = QtWidgets.QLabel(self.History)
        self.H2_2.setGeometry(QtCore.QRect(140, 440, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.H2_2.sizePolicy().hasHeightForWidth())
        self.H2_2.setSizePolicy(sizePolicy)
        self.H2_2.setText("")
        self.H2_2.setObjectName("H2_2")
        self.label_17 = QtWidgets.QLabel(self.History)
        self.label_17.setGeometry(QtCore.QRect(140, 500, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: #8e2426;")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.C2_2 = QtWidgets.QLabel(self.History)
        self.C2_2.setGeometry(QtCore.QRect(140, 140, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.C2_2.sizePolicy().hasHeightForWidth())
        self.C2_2.setSizePolicy(sizePolicy)
        self.C2_2.setText("")
        self.C2_2.setObjectName("C2_2")
        self.C7_2 = QtWidgets.QLabel(self.History)
        self.C7_2.setGeometry(QtCore.QRect(440, 140, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.C7_2.sizePolicy().hasHeightForWidth())
        self.C7_2.setSizePolicy(sizePolicy)
        self.C7_2.setText("")
        self.C7_2.setObjectName("C7_2")
        self.D2_2 = QtWidgets.QLabel(self.History)
        self.D2_2.setGeometry(QtCore.QRect(140, 200, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D2_2.sizePolicy().hasHeightForWidth())
        self.D2_2.setSizePolicy(sizePolicy)
        self.D2_2.setText("")
        self.D2_2.setObjectName("D2_2")
        self.G2_2 = QtWidgets.QLabel(self.History)
        self.G2_2.setGeometry(QtCore.QRect(140, 380, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.G2_2.sizePolicy().hasHeightForWidth())
        self.G2_2.setSizePolicy(sizePolicy)
        self.G2_2.setText("")
        self.G2_2.setObjectName("G2_2")
        self.G4_2 = QtWidgets.QLabel(self.History)
        self.G4_2.setGeometry(QtCore.QRect(260, 380, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.G4_2.sizePolicy().hasHeightForWidth())
        self.G4_2.setSizePolicy(sizePolicy)
        self.G4_2.setText("")
        self.G4_2.setObjectName("G4_2")
        self.C1_2 = QtWidgets.QLabel(self.History)
        self.C1_2.setGeometry(QtCore.QRect(80, 140, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.C1_2.sizePolicy().hasHeightForWidth())
        self.C1_2.setSizePolicy(sizePolicy)
        self.C1_2.setText("")
        self.C1_2.setObjectName("C1_2")
        self.line_4 = QtWidgets.QFrame(self.History)
        self.line_4.setGeometry(QtCore.QRect(560, 0, 20, 561))
        self.line_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_4.setLineWidth(2)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setObjectName("line_4")
        self.list_moves_2 = QtWidgets.QListWidget(self.History)
        self.list_moves_2.setGeometry(QtCore.QRect(580, 100, 201, 401))
        self.list_moves_2.setObjectName("list_moves_2")
        self.line_5 = QtWidgets.QFrame(self.History)
        self.line_5.setGeometry(QtCore.QRect(570, 40, 221, 16))
        self.line_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_5.setLineWidth(2)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setObjectName("line_5")
        self.round_2 = QtWidgets.QLabel(self.History)
        self.round_2.setGeometry(QtCore.QRect(600, 5, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.round_2.setFont(font)
        self.round_2.setAlignment(QtCore.Qt.AlignCenter)
        self.round_2.setObjectName("round_2")
        self.label_19 = QtWidgets.QLabel(self.History)
        self.label_19.setGeometry(QtCore.QRect(590, 60, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.next = QtWidgets.QPushButton(self.History)
        self.next.setGeometry(QtCore.QRect(690, 530, 75, 23))
        self.next.setObjectName("next")
        self.line_6 = QtWidgets.QFrame(self.History)
        self.line_6.setGeometry(QtCore.QRect(570, 510, 221, 16))
        self.line_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_6.setLineWidth(2)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setObjectName("line_6")
        self.back = QtWidgets.QPushButton(self.History)
        self.back.setGeometry(QtCore.QRect(590, 530, 75, 23))
        self.back.setObjectName("back")
        self.area_2.raise_()
        self.B6_2.raise_()
        self.B7_2.raise_()
        self.label_H_2.raise_()
        self.A5_2.raise_()
        self.E1_2.raise_()
        self.B2_2.raise_()
        self.H4_2.raise_()
        self.H8_2.raise_()
        self.label_10.raise_()
        self.F6_2.raise_()
        self.A8_2.raise_()
        self.D6_2.raise_()
        self.label_B_2.raise_()
        self.H1_2.raise_()
        self.E8_2.raise_()
        self.E5_2.raise_()
        self.label_11.raise_()
        self.D7_2.raise_()
        self.A6_2.raise_()
        self.F1_2.raise_()
        self.B5_2.raise_()
        self.A3_2.raise_()
        self.A7_2.raise_()
        self.G5_2.raise_()
        self.F3_2.raise_()
        self.D4_2.raise_()
        self.label_12.raise_()
        self.C4_2.raise_()
        self.C5_2.raise_()
        self.label_13.raise_()
        self.H3_2.raise_()
        self.label_F_2.raise_()
        self.C3_2.raise_()
        self.F8_2.raise_()
        self.G7_2.raise_()
        self.label_14.raise_()
        self.A2_2.raise_()
        self.A4_2.raise_()
        self.H5_2.raise_()
        self.D1_2.raise_()
        self.B4_2.raise_()
        self.C6_2.raise_()
        self.F4_2.raise_()
        self.D8_2.raise_()
        self.B3_2.raise_()
        self.H6_2.raise_()
        self.B1_2.raise_()
        self.F7_2.raise_()
        self.H7_2.raise_()
        self.F5_2.raise_()
        self.A1_2.raise_()
        self.label_15.raise_()
        self.label_A_2.raise_()
        self.D3_2.raise_()
        self.label_E_2.raise_()
        self.D5_2.raise_()
        self.G6_2.raise_()
        self.label_G_2.raise_()
        self.G8_2.raise_()
        self.label_C_2.raise_()
        self.B8_2.raise_()
        self.E7_2.raise_()
        self.label_D_2.raise_()
        self.C8_2.raise_()
        self.E3_2.raise_()
        self.label_16.raise_()
        self.E6_2.raise_()
        self.G1_2.raise_()
        self.E4_2.raise_()
        self.F2_2.raise_()
        self.A_2.raise_()
        self.E2_2.raise_()
        self.G3_2.raise_()
        self.H2_2.raise_()
        self.label_17.raise_()
        self.C2_2.raise_()
        self.C7_2.raise_()
        self.D2_2.raise_()
        self.G2_2.raise_()
        self.G4_2.raise_()
        self.C1_2.raise_()
        self.line_4.raise_()
        self.list_moves_2.raise_()
        self.line_5.raise_()
        self.round_2.raise_()
        self.label_19.raise_()
        self.next.raise_()
        self.line_6.raise_()
        self.back.raise_()
        self.tabWidget.addTab(self.History, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Chess"))
        self.label_C.setText(_translate("MainWindow", "C"))
        self.label_1.setText(_translate("MainWindow", "1"))
        self.label_F.setText(_translate("MainWindow", "F"))
        self.label_8.setText(_translate("MainWindow", "8"))
        self.label_3.setText(_translate("MainWindow", "3"))
        self.label_B.setText(_translate("MainWindow", "B"))
        self.label_6.setText(_translate("MainWindow", "6"))
        self.label_E.setText(_translate("MainWindow", "E"))
        self.label_H.setText(_translate("MainWindow", "H"))
        self.label_D.setText(_translate("MainWindow", "D"))
        self.label_4.setText(_translate("MainWindow", "4"))
        self.label_G.setText(_translate("MainWindow", "G"))
        self.label_A.setText(_translate("MainWindow", "A"))
        self.label_2.setText(_translate("MainWindow", "2"))
        self.label_7.setText(_translate("MainWindow", "7"))
        self.label_5.setText(_translate("MainWindow", "5"))
        self.leave.setText(_translate("MainWindow", "Сдаться"))
        self.exit.setText(_translate("MainWindow", "Выход"))
        self.choose_piece_text.setText(_translate("MainWindow", "Фигура выбрана:"))
        self.label_9.setText(_translate("MainWindow", "История ходов"))
        self.player_move.setText(_translate("MainWindow", "Ходит: "))
        self.return_to_menu.setText(_translate("MainWindow", "Вернуться в меню"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Game), _translate("MainWindow", "Game"))
        self.label_H_2.setText(_translate("MainWindow", "H"))
        self.label_10.setText(_translate("MainWindow", "5"))
        self.label_B_2.setText(_translate("MainWindow", "B"))
        self.label_11.setText(_translate("MainWindow", "6"))
        self.label_12.setText(_translate("MainWindow", "3"))
        self.label_13.setText(_translate("MainWindow", "1"))
        self.label_F_2.setText(_translate("MainWindow", "F"))
        self.label_14.setText(_translate("MainWindow", "8"))
        self.label_15.setText(_translate("MainWindow", "7"))
        self.label_A_2.setText(_translate("MainWindow", "A"))
        self.label_E_2.setText(_translate("MainWindow", "E"))
        self.label_G_2.setText(_translate("MainWindow", "G"))
        self.label_C_2.setText(_translate("MainWindow", "C"))
        self.label_D_2.setText(_translate("MainWindow", "D"))
        self.label_16.setText(_translate("MainWindow", "4"))
        self.label_17.setText(_translate("MainWindow", "2"))
        self.round_2.setText(_translate("MainWindow", "Ход: Чёрного  Белого"))
        self.label_19.setText(_translate("MainWindow", "История ходов"))
        self.next.setText(_translate("MainWindow", "-->"))
        self.back.setText(_translate("MainWindow", "<--"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.History), _translate("MainWindow", "History"))
